version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8  # You can choose the image that matches your Python version
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            python -m unittest test

  deploy:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker build -t yourdockerhubusername/dockerimage_circleci .
            docker push yourdockerhubusername/dockerimage_circleci

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main  # or any branch you want to deploy from
